version: "3.9"

services:
  parse_github_issue:
    build: 
      context: .
      dockerfile: services/github_issue/Dockerfile
    container_name: parse-github-issue
    env_file:
      - services/github_issue/.env
    ports:
      - "8000:8000"
    restart: unless-stopped

  translate:
    build:
      context: .
      dockerfile: services/translate/Dockerfile
    container_name: translate

    ports:
      - "8001:8001"

    volumes:
      - huggingface_cache:/models

    environment:
      HF_HOME: /models
      TRANSFORMERS_CACHE: /models

    restart: unless-stopped

  md_to_html:
    build: 
      context: .
      dockerfile: services/md_to_html/Dockerfile
    container_name: markdown-to-html
    ports:
      - "3000:3000"
    restart: unless-stopped

  postgres:
    image: postgres:15-alpine
    container_name: parse_job_posting_db
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_INITDB_ARGS: "--encoding=UTF8 --lc-collate=C --lc-ctype=C"
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./data:/docker-entrypoint-initdb.d
      - ./sql:/sql
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 30s
      timeout: 10s
      retries: 3
    networks:
      - default

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: parse_job_posting_pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_PASSWORD}
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    ports:
      - "8080:80"
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    depends_on:
      - postgres
    restart: unless-stopped
    networks:
      - default

  parse_job_posting:
    build: 
      context: .
      dockerfile: services/job_parser/Dockerfile
    container_name: parse-job-posting
    networks:
      - shared-net
      - default
    env_file:
      - .env
      - services/job_parser/.env
    depends_on:
      - postgres
    ports:
      - "9001:9001"
    restart: unless-stopped

  skill_manager:
    build: 
      context: .
      dockerfile: services/skill_manager/Dockerfile
    container_name: manage-skills
    env_file:
      - .env
      - services/skill_manager/.env
    depends_on:
      - postgres
    networks:
      - default
    ports:
      - "9002:9002"
    restart: unless-stopped

volumes:
  huggingface_cache:
  postgres_data:
  pgadmin_data:

networks:
  default:
    name: postgresql_overview_network

  shared-net:
    external: true
    name: shared-network
