[project]
name = "my-platform"
version = "0.1.0"
requires-python = ">=3.13"
dependencies = [
    "datamodel-code-generator>=0.72.4",
]

[tool.uv.workspace]
members = [
  "services/*",
  "shared",
  "scripts/pytools"
]
exclude = ["services/md_to_html", "services/job_matcher"]

[dependency-groups]
dev = [
  "pytest>=8.4",
  "pytest-asyncio>=1.1",
  "ruff>=0.12",
  "mypy>=1.17",
  "poethepoet>=0.48.0",
]

[tool.ruff]
line-length = 100
target-version = "py313"
ignore = ["E402"]
indent-width = 2

[tool.ruff.lint]
select = ["E", "F", "I", "UP", "B"]

[tool.pytest.ini_options]
testpaths = ["tests"]

[tool.mypy]
python_version = "3.13"
strict = true
explicit_package_bases = true

[tool.poe.tasks]
install_all = "uv sync --package common --package parse-github-issue --package my-platform --package tools --package translate --package parse-job-postin --package job-skills --package skill-synonymsg --package skills"
lint = "ruff check ."
format = "ruff format ."
mypy = "mypy ."
