/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/filter": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Filter Skills */
        get: operations["filter_skills_filter_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/categories": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Categories */
        get: operations["categories_categories_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/job-skill": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create */
        post: operations["create_job_skill_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** CreateRequest */
        CreateRequest: {
            /** Normalizedtext */
            normalizedText: string;
            /** Url */
            url: string;
        };
        /** CreateResponse */
        CreateResponse: Record<string, never>;
        /**
         * Familiarity
         * @enum {string}
         */
        Familiarity: "know-in-depth" | "study" | "actively-using" | "know-a-bit" | "unknown";
        /** FilterSkillsResponse */
        FilterSkillsResponse: {
            /** Skills */
            skills: components["schemas"]["Skill"][];
            /** Totalrows */
            totalRows: number;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** Skill */
        Skill: {
            /** Normalizedtext */
            normalizedText: string;
            /** Companycount */
            companyCount: number;
            /** Companies */
            companies: string[];
            /** Categories */
            categories: string[];
            /** Synonyms */
            synonyms: string[];
            /** Synonymtexts */
            synonymTexts: string[];
            /** Urls */
            urls: string[];
            familiarity: components["schemas"]["Familiarity"];
            temperature: components["schemas"]["Temperature"];
            type: components["schemas"]["SkillType"];
            /** Displaytext */
            displayText: string;
        };
        /**
         * SkillType
         * @enum {string}
         */
        SkillType: "Approach" | "Application" | "Non-skill";
        /**
         * Temperature
         * @enum {string}
         */
        Temperature: "interested" | "meh" | "avoid!";
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    filter_skills_filter_get: {
        parameters: {
            query?: {
                currentPage?: number;
                pageSize?: number;
                search?: string;
                category?: string;
                sort?: "name" | "companyCount";
                type?: components["schemas"]["SkillType"] | null;
                familiarity?: components["schemas"]["Familiarity"] | null;
                temperature?: components["schemas"]["Temperature"] | null;
                jobUrl?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FilterSkillsResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    categories_categories_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": string[];
                };
            };
        };
    };
    create_job_skill_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CreateResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
