/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/synonym": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get All Skill Synonyms */
        get: operations["get_all_skill_synonyms_synonym_get"];
        put?: never;
        /** Create Synonym */
        post: operations["create_synonym_synonym_post"];
        /** Remove Synonym */
        delete: operations["remove_synonym_synonym_delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/skill": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Skills */
        get: operations["get_skills_skill_get"];
        /** Edit */
        put: operations["edit_skill_put"];
        /** Create */
        post: operations["create_skill_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/skill-texts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Skill Texts */
        get: operations["get_skill_texts_skill_texts_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** CreateRequest */
        CreateRequest: {
            /** Displaytext */
            displayText: string;
            /** Normalizedtext */
            normalizedText: string;
        };
        /** CreateResponse */
        CreateResponse: {
            /** Normalizedtext */
            normalizedText: string;
            /** Displaytext */
            displayText: string;
            type: components["schemas"]["SkillType"];
            familiarity: components["schemas"]["Familiarity"];
            temperature: components["schemas"]["Temperature"];
        };
        /** CreateSynonymRequest */
        CreateSynonymRequest: {
            /** Originnormalizedtext */
            originNormalizedText: string;
            /** Normalizedtext */
            normalizedText: string;
        };
        /** CreateSynonymResponse */
        CreateSynonymResponse: {
            /** Originnormalizedtext */
            originNormalizedText: string;
            /** Normalizedtext */
            normalizedText: string;
        };
        /** EditRequest */
        EditRequest: {
            /** Normalizedtext */
            normalizedText: string;
            skillType?: components["schemas"]["SkillType"] | null;
            familiarity?: components["schemas"]["Familiarity"] | null;
            temperature?: components["schemas"]["Temperature"] | null;
        };
        /** EditResponse */
        EditResponse: Record<string, never>;
        /**
         * Familiarity
         * @enum {string}
         */
        Familiarity: "know-in-depth" | "study" | "actively-using" | "know-a-bit" | "unknown";
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** HealthResponse */
        HealthResponse: {
            /** Status */
            status: string;
        };
        /** RemoveSynonymRequest */
        RemoveSynonymRequest: {
            /** Originnormalizedtext */
            originNormalizedText: string;
            /** Normalizedtext */
            normalizedText: string;
            /** Displaytext */
            displayText: string;
        };
        /** RemoveSynonymResponse */
        RemoveSynonymResponse: {
            /** Originnormalizedtext */
            originNormalizedText: string;
            /** Normalizedtext */
            normalizedText: string;
            /** Displaytext */
            displayText: string;
        };
        /** Skill */
        Skill: {
            /** Normalizedtext */
            normalizedText: string;
            /** Text */
            text: string;
            type: components["schemas"]["SkillType"];
            familiarity: components["schemas"]["Familiarity"];
            temperature: components["schemas"]["Temperature"];
            /**
             * Createdat
             * Format: date-time
             */
            createdAt: string;
            /**
             * Updatedat
             * Format: date-time
             */
            updatedAt: string;
        };
        /** SkillSynonym */
        SkillSynonym: {
            /** Text */
            text: string;
            /** Originnormalizedtext */
            originNormalizedText: string;
            /** Normalizedtext */
            normalizedText: string;
            /**
             * Createdat
             * Format: date-time
             */
            createdAt: string;
            /**
             * Updatedat
             * Format: date-time
             */
            updatedAt: string;
        };
        /** SkillSynonymsResponse */
        SkillSynonymsResponse: {
            /** Skills */
            skills: components["schemas"]["SkillSynonym"][];
        };
        /** SkillText */
        SkillText: {
            /** Normalizedtext */
            normalizedText: string;
            /** Displaytext */
            displayText: string;
        };
        /** SkillTextsResponse */
        SkillTextsResponse: {
            /** Texts */
            texts: components["schemas"]["SkillText"][];
        };
        /**
         * SkillType
         * @enum {string}
         */
        SkillType: "Approach" | "Application" | "Non-skill";
        /** SkillsRequest */
        SkillsRequest: {
            /** Skillids */
            skillIds: string[];
        };
        /** SkillsResponse */
        SkillsResponse: {
            /** Skills */
            skills: components["schemas"]["Skill"][];
        };
        /**
         * Temperature
         * @enum {string}
         */
        Temperature: "interested" | "meh" | "avoid!";
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
    get_all_skill_synonyms_synonym_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SkillSynonymsResponse"];
                };
            };
        };
    };
    create_synonym_synonym_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateSynonymRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CreateSynonymResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    remove_synonym_synonym_delete: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RemoveSynonymRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RemoveSynonymResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_skills_skill_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SkillsRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SkillsResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    edit_skill_put: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["EditRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EditResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_skill_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CreateResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_skill_texts_skill_texts_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SkillTextsResponse"];
                };
            };
        };
    };
}
