"""Change skill synonym index

Revision ID: 0dc0154beea7
Revises: f2135cd2439d
Create Date: 2026-08-08 16:05:19.138897

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0dc0154beea7'
down_revision: Union[str, Sequence[str], None] = 'f2135cd2439d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('skill_synonyms_origin_normalized_text_key'), 'skill_synonyms', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(op.f('skill_synonyms_origin_normalized_text_key'), 'skill_synonyms', ['origin_normalized_text'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
