"""Initial

Revision ID: 216bb6cdd829
Revises:
Create Date: 2026-08-08 10:37:46.366064

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "216bb6cdd829"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
  """Upgrade schema."""
  # ### commands auto generated by Alembic - please adjust! ###
  op.create_table(
    "job_posting_histories",
    sa.Column("url", sa.String(length=1024), nullable=False),
    sa.Column("body", sa.String(length=10240), nullable=False),
    sa.Column("category", sa.String(length=100), nullable=False),
    sa.Column("company", sa.String(length=100), nullable=False),
    sa.Column(
      "created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=True
    ),
    sa.PrimaryKeyConstraint("url"),
  )
  op.create_index(
    op.f("ix_job_posting_histories_category"),
    "job_posting_histories",
    ["category"],
    unique=False,
  )
  op.create_index(
    op.f("ix_job_posting_histories_company"), "job_posting_histories", ["company"], unique=False
  )
  op.create_table(
    "job_postings",
    sa.Column("url", sa.String(length=1024), nullable=False),
    sa.Column("body", sa.String(length=10240), nullable=False),
    sa.Column("category", sa.String(length=100), nullable=False),
    sa.Column("company", sa.String(length=100), nullable=False),
    sa.Column(
      "created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=True
    ),
    sa.Column(
      "updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=True
    ),
    sa.PrimaryKeyConstraint("url"),
  )
  op.create_index(op.f("ix_job_postings_category"), "job_postings", ["category"], unique=False)
  op.create_index(op.f("ix_job_postings_company"), "job_postings", ["company"], unique=False)
  op.create_table(
    "skill_synonyms",
    sa.Column("text", sa.String(length=50), nullable=False),
    sa.Column("normalized_text", sa.String(length=50), nullable=False),
    sa.Column(
      "created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=True
    ),
    sa.Column(
      "updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=True
    ),
    sa.PrimaryKeyConstraint("text"),
    sa.UniqueConstraint("normalized_text"),
  )
  op.create_table(
    "skills",
    sa.Column("normalized_text", sa.String(length=50), nullable=False),
    sa.Column("text", sa.String(length=50), nullable=False),
    sa.Column(
      "type",
      sa.Enum("APPROACH", "APPLICATION", "NON_SKILL", name="skilltype"),
      nullable=False,
    ),
    sa.Column(
      "familiarity",
      sa.Enum(
        "KNOW_IN_DEPTH",
        "STUDY",
        "ACTIVELY_STUDYING",
        "KNOW_A_BIT",
        "UNKNOWN",
        name="familiarity",
      ),
      nullable=False,
    ),
    sa.Column(
      "temperature", sa.Enum("INTERESTED", "MEH", "AVOID", name="temperature"), nullable=False
    ),
    sa.Column(
      "created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=True
    ),
    sa.Column(
      "updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=True
    ),
    sa.PrimaryKeyConstraint("normalized_text"),
    sa.UniqueConstraint("text"),
  )
  op.create_index(op.f("ix_skills_familiarity"), "skills", ["familiarity"], unique=False)
  op.create_index(op.f("ix_skills_temperature"), "skills", ["temperature"], unique=False)
  op.create_index(op.f("ix_skills_type"), "skills", ["type"], unique=False)
  # ### end Alembic commands ###


def downgrade() -> None:
  """Downgrade schema."""
  # ### commands auto generated by Alembic - please adjust! ###
  op.create_table(
    "alembic_version_service_skill_manager",
    sa.Column("version_num", sa.VARCHAR(length=32), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint("version_num", name=op.f("alembic_version_service_skill_manager_pkc")),
  )
  op.drop_index(op.f("ix_skills_type"), table_name="skills")
  op.drop_index(op.f("ix_skills_temperature"), table_name="skills")
  op.drop_index(op.f("ix_skills_familiarity"), table_name="skills")
  op.drop_table("skills")
  op.drop_table("skill_synonyms")
  op.drop_index(op.f("ix_job_postings_company"), table_name="job_postings")
  op.drop_index(op.f("ix_job_postings_category"), table_name="job_postings")
  op.drop_table("job_postings")
  op.drop_index(op.f("ix_job_posting_histories_company"), table_name="job_posting_histories")
  op.drop_index(op.f("ix_job_posting_histories_category"), table_name="job_posting_histories")
  op.drop_table("job_posting_histories")
  # ### end Alembic commands ###
