"""Add Synonym text length

Revision ID: 24f555e66eee
Revises: 0dc0154beea7
Create Date: 2026-08-08 16:44:10.877266

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "24f555e66eee"
down_revision: str | Sequence[str] | None = "0dc0154beea7"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
  """Upgrade schema."""
  # ### commands auto generated by Alembic - please adjust! ###
  op.add_column(
    "skill_synonyms",
    sa.Column(
      "text_length",
      sa.Integer(),
      sa.Computed(
        "char_length(text)",
      ),
      nullable=False,
    ),
  )
  # ### end Alembic commands ###


def downgrade() -> None:
  """Downgrade schema."""
  # ### commands auto generated by Alembic - please adjust! ###
  op.drop_column("skill_synonyms", "text_length")
  # ### end Alembic commands ###
