"""Increase body size

Revision ID: 45e30c74e472
Revises: 793dcf486fa5
Create Date: 2026-08-13 23:32:35.968085

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "45e30c74e472"
down_revision: str | Sequence[str] | None = "793dcf486fa5"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
  """Upgrade schema."""
  # ### commands auto generated by Alembic - please adjust! ###
  op.alter_column(
    "job_posting_histories",
    "body",
    existing_type=sa.VARCHAR(length=10240),
    type_=sa.String(length=51200),
    existing_nullable=False,
  )
  op.alter_column(
    "job_postings",
    "body",
    existing_type=sa.VARCHAR(length=10240),
    type_=sa.String(length=51200),
    existing_nullable=False,
  )
  # ### end Alembic commands ###


def downgrade() -> None:
  """Downgrade schema."""
  # ### commands auto generated by Alembic - please adjust! ###
  op.alter_column(
    "job_postings",
    "body",
    existing_type=sa.String(length=51200),
    type_=sa.VARCHAR(length=10240),
    existing_nullable=False,
  )
  op.alter_column(
    "job_posting_histories",
    "body",
    existing_type=sa.String(length=51200),
    type_=sa.VARCHAR(length=10240),
    existing_nullable=False,
  )
  # ### end Alembic commands ###
