"""Skill synonym group ignore

Revision ID: 4fa48b33cd66
Revises: 45e30c74e472
Create Date: 2026-08-15 20:44:07.200329

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "4fa48b33cd66"
down_revision: Union[str, Sequence[str], None] = "45e30c74e472"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
  """Upgrade schema."""
  # ### commands auto generated by Alembic - please adjust! ###
  op.create_table(
    "ignored_synonym_group",
    sa.Column("id", sa.String(length=1024), nullable=False),
    sa.Column(
      "created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=True
    ),
    sa.Column(
      "updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=True
    ),
    sa.PrimaryKeyConstraint("id"),
  )
  # ### end Alembic commands ###


def downgrade() -> None:
  """Downgrade schema."""
  # ### commands auto generated by Alembic - please adjust! ###
  op.drop_table("ignored_synonym_group")
  # ### end Alembic commands ###
