"""Job Posting SKill

Revision ID: 793dcf486fa5
Revises: 24f555e66eee
Create Date: 2026-08-09 16:57:24.962788

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '793dcf486fa5'
down_revision: Union[str, Sequence[str], None] = '24f555e66eee'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('job_posting_skills',
    sa.Column('job_url', sa.String(length=1024), nullable=False),
    sa.Column('skill_normalized_text', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('job_url', 'skill_normalized_text')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('job_posting_skills')
    # ### end Alembic commands ###
