"""Remove Job posting history url as primary key

Revision ID: b692b7a838e4
Revises: 4fa48b33cd66
Create Date: 2026-08-17 00:00:42.844838

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b692b7a838e4'
down_revision: Union[str, Sequence[str], None] = '4fa48b33cd66'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('job_posting_histories', sa.Column('id', sa.UUID(), nullable=True))
    op.execute("UPDATE job_posting_histories SET id = gen_random_uuid() WHERE id IS NULL")
    op.create_index(op.f('ix_job_posting_histories_url'), 'job_posting_histories', ['url'], unique=False)
    op.alter_column('job_posting_histories', 'id', nullable=False, unique=True)
    op.drop_constraint('job_posting_histories_pkey', 'job_posting_histories', type_='primary')
    op.create_primary_key('pk_job_posting_histories_id', 'job_posting_histories', ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    op.drop_constraint('pk_job_posting_histories_id', 'job_posting_histories', type_='primary')
    op.alter_column('job_posting_histories', 'id', nullable=True, unique=False)
    op.create_primary_key(
        'job_posting_histories_pkey',
        'job_posting_histories',
        ['url'],
    )
    op.drop_index(op.f('ix_job_posting_histories_url'), table_name='job_posting_histories')
    op.drop_column('job_posting_histories', 'id')
    # ### end Alembic commands ###
