"""Skills

Revision ID: f2135cd2439d
Revises: 216bb6cdd829
Create Date: 2026-08-08 15:09:50.760640

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "f2135cd2439d"
down_revision: str | Sequence[str] | None = "216bb6cdd829"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
  """Upgrade schema."""
  # ### commands auto generated by Alembic - please adjust! ###
  op.add_column(
    "skill_synonyms", sa.Column("origin_normalized_text", sa.String(length=50), nullable=False)
  )
  op.drop_constraint(op.f("skill_synonyms_normalized_text_key"), "skill_synonyms", type_="unique")
  op.create_unique_constraint(None, "skill_synonyms", ["origin_normalized_text"])
  # ### end Alembic commands ###


def downgrade() -> None:
  """Downgrade schema."""
  # ### commands auto generated by Alembic - please adjust! ###
  op.drop_constraint(None, "skill_synonyms", type_="unique")
  op.create_unique_constraint(
    op.f("skill_synonyms_normalized_text_key"),
    "skill_synonyms",
    ["normalized_text"],
    postgresql_nulls_not_distinct=False,
  )
  op.drop_column("skill_synonyms", "origin_normalized_text")
  # ### end Alembic commands ###
