[project]
name = "skill-synonyms"
version = "0.1.0"
requires-python = ">=3.13"

dependencies = [
  "fastapi==0.139.2",
  "uvicorn[standard]==0.51.0",
  "pydantic",
  "requests",
  "asyncpg",
  "alembic",
  "SQLAlchemy",
  "python-dotenv",
  "greenlet>=3.5.4",
  "psycopg2-binary>=2.9.12",
  "rapidfuzz"
]
